
# CaseTcl core
# Copyright (c) 2016, Scientech LLC.
# All rights reserved.

include 'lexer/preprocessor.tcl'
include 'lexer/preprocess_file.tcl'
include 'lexer/convert_line.tcl'
include 'lexer/lower_case.tcl'
include 'lexer/get_directive.tcl'
include 'lexer/preprocess_line.tcl'
include 'lexer/get_preprocessor_symbol.tcl'
include 'lexer/add_preprocessor_symbol.tcl'
include 'lexer/define_fix_constant.tcl'
include 'lexer/define_equ_constant.tcl'
include 'lexer/define_symbolic_constant.tcl'
include 'lexer/define_struc.tcl'
include 'lexer/define_macro.tcl'
include 'lexer/postpone_directive.tcl'
include 'lexer/rept_directive.tcl'
include 'lexer/irp_directive.tcl'
include 'lexer/irps_directive.tcl'
include 'lexer/irpv_directive.tcl'
include 'lexer/match_directive.tcl'
include 'lexer/define_instant_macro.tcl'
include 'lexer/prepare_match.tcl'
include 'lexer/purge_macro.tcl'
include 'lexer/purge_struc.tcl'
include 'lexer/restore_equ_constant.tcl'
include 'lexer/process_fix_constants.tcl'
include 'lexer/process_equ_constants.tcl'
include 'lexer/process_macro_operators.tcl'
include 'lexer/use_macro.tcl'
include 'lexer/use_instant_macro.tcl'
include 'lexer/do_irp.tcl'
include 'lexer/do_match.tcl'
include 'lexer/process_macro.tcl'
include 'lexer/local_symbols.tcl'
include 'lexer/common_block.tcl'
include 'lexer/forward_block.tcl'
include 'lexer/reverse_block.tcl'
include 'lexer/close_macro_block.tcl'
include 'lexer/get_macro_symbol.tcl'
include 'lexer/add_macro_symbol.tcl'
include 'lexer/include_file.tcl'

